name: Build

on:
    push:
    workflow_dispatch:

jobs:
    build:
        name: Linux build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install deps (Linux)
              run: |
                  sudo apt-get update
                  sudo apt-get install libreadline-dev xxd libffi-dev libssl-dev cmake

            - name: Install just
              uses: taiki-e/install-action@v2
              with:
                  tool: just

            - name: Fetch tags
              run: git fetch --tags --force origin

            - name: Configure CMake
              run: just preset=linux-release configure

            - name: Build
              run: just preset=linux-release build

            - name: Test
              run: just preset=linux-release test
